apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bvf8ab5cd-go 
  janus-idp.io/tekton: bvf8ab5cd-go
  backstage.io/kubernetes-id: bvf8ab5cd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bvf8ab5cd-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml